# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlikiUi/OknoGeneratoraHasel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog5(object):
    def setupUi(self, Dialog5):
        Dialog5.setObjectName("Dialog5")
        Dialog5.resize(282, 430)
        self.pushButton = QtWidgets.QPushButton(Dialog5)
        self.pushButton.setGeometry(QtCore.QRect(140, 390, 131, 31))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Dialog5)
        self.label.setGeometry(QtCore.QRect(20, 390, 111, 31))
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog5)
        self.textBrowser.setGeometry(QtCore.QRect(10, 40, 261, 341))
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(Dialog5)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 251, 21))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog5)
        QtCore.QMetaObject.connectSlotsByName(Dialog5)

    def retranslateUi(self, Dialog5):
        _translate = QtCore.QCoreApplication.translate
        Dialog5.setWindowTitle(_translate("Dialog5", "Generator Haseł"))
        self.pushButton.setText(_translate("Dialog5", "Generuj"))
        self.label.setText(_translate("Dialog5", "Generowanie haseł:"))
        self.textBrowser.setHtml(_translate("Dialog5", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">1. Zostanie wygenerowany plik z loginami i hasłami użytkowników.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">2. Po wyłączeniu aplikacji zostanie on przez aplikację usunięty.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">3. Koniecznym jest wydrukowanie stworzonego pliku.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">4. Następnie przekazaniu poszczególnych haseł do odpowiednich użytkowników.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">5. Po naciśnięciu przycisku aktualnie zalogowani użytkownicy nie będą mogli ponownie zalogować się na swoje konta.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-style:italic;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">Pamiętaj, że każde udostępnianie powierzonych danych osobom do tego nieupowarznionym jest poważnym naruszeniem bezpieczeństwa.</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog5", "Przypomnienie:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog5 = QtWidgets.QDialog()
    ui = Ui_Dialog5()
    ui.setupUi(Dialog5)
    Dialog5.show()
    sys.exit(app.exec_())
